version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  server:
    restart: on-failure
    depends_on:
      - mongo
    build:
      context: ../../server
      dockerfile: Dockerfile-develop
    ports:
      - "8000:8000"
    links:
      - mongo
  client:
    restart: on-failure
    depends_on:
      - server
    build:
      context: ../../client
      dockerfile: Dockerfile-deploy
    environment:
      - API_BASE_URL = "server/api/"
    ports:
      - "80:80"
    links:
      - server
volumes:
  mongodata:
